"""add violations table

Revision ID: 23f90d7c8448
Revises: 30d6136aa16a
Create Date: 2026-03-23 09:57:36.537111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f90d7c8448'
down_revision = '30d6136aa16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.Enum('no_face', 'multiple_faces', 'gaze_off', 'head_turned', 'tab_switch', 'phone_detected', 'unknown_object', 'audio_detected', name='violationtype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('violation_metadata', sa.JSON(), nullable=True),
    sa.Column('snapshot_path', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violations')
    # ### end Alembic commands ###
